# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1598262320);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1598316932);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1598337068);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1598262200);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1598320652);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150114162216");
user_pref("browser.slowStartup.averageTime", 2450);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20150114162216");
user_pref("browser.startup.homepage_override.mstone", "31.4.0");
user_pref("datareporting.healthreport.lastDataSubmissionFailureTime", "1598316894378");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1598316847197");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1596766370918");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1598403294378");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1595898023421");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1595926861302");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-implicit-time-elapsed");
user_pref("datareporting.policy.firstRunTime", "1595828410562");
user_pref("datareporting.sessions.current.activeTicks", 7);
user_pref("datareporting.sessions.current.firstPaint", 1735);
user_pref("datareporting.sessions.current.main", 411);
user_pref("datareporting.sessions.current.sessionRestored", 1821);
user_pref("datareporting.sessions.current.startTime", "1596100491544");
user_pref("datareporting.sessions.current.totalTime", 2159124);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.prunedIndex", 0);
user_pref("extensions.blocklist.pingCountTotal", 12);
user_pref("extensions.blocklist.pingCountVersion", 12);
user_pref("extensions.bootstrappedAddons", "{\"langpack-zh-CN@firefox.mozilla.org\":{\"version\":\"31.4.0\",\"type\":\"locale\",\"descriptor\":\"/home/esun/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/langpack-zh-CN@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.4.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1594116611000,\"rdfTime\":1421253544000}}},{\"name\":\"app-system-user\",\"addons\":{\"langpack-zh-CN@firefox.mozilla.org\":{\"descriptor\":\"/home/esun/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/langpack-zh-CN@firefox.mozilla.org.xpi\",\"mtime\":1421253594000}}}]");
user_pref("extensions.lastAppVersion", "31.4.0");
user_pref("extensions.lastPlatformVersion", "31.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20150114162216");
user_pref("gecko.mstone", "31.4.0");
user_pref("idle.lastDailyNotification", 1598340199);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1598259584);
user_pref("places.history.expiration.transient_current_max_pages", 25681);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1595829122);
user_pref("toolkit.startup.last_success", 1596100491);
user_pref("toolkit.telemetry.previousBuildID", "20150114162216");
